//! Deterministic shell completion generated from the production command registry.

use std::fmt::{self, Write as _};

use crate::cli::definition::command_descriptors;

/// Error returned when completion is requested for an unsupported shell.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompletionError {
    shell: String,
}

impl fmt::Display for CompletionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "unsupported completion shell {:?}; expected bash, zsh, fish, or powershell",
            self.shell
        )
    }
}

impl std::error::Error for CompletionError {}

/// Generate a static completion script for a supported shell.
///
/// The command candidates and descriptions come directly from the production
/// registry. The generated completer only participates at the command position;
/// it does not claim or reinterpret arguments belonging to Git passthrough.
pub fn generate_completion(shell: &str) -> Result<String, CompletionError> {
    let normalized = shell.trim().to_ascii_lowercase();
    match normalized.as_str() {
        "bash" => Ok(bash()),
        "zsh" => Ok(zsh()),
        "fish" => Ok(fish()),
        "powershell" | "pwsh" => Ok(powershell()),
        _ => Err(CompletionError {
            shell: shell.to_owned(),
        }),
    }
}

fn bash() -> String {
    let words = command_descriptors()
        .into_iter()
        .map(|descriptor| descriptor.claim.name)
        .collect::<Vec<_>>()
        .join(" ");
    format!(
        r#"# Generated by jjk from its production command registry.
_jjk_completion() {{
    if (( COMP_CWORD != 1 )); then
        # JJK owns only its registered command position; delegate every argument to Git.
        if declare -F __git_main >/dev/null; then
            local saved_command=${{COMP_WORDS[0]}}
            COMP_WORDS[0]=git
            __git_main
            COMP_WORDS[0]=$saved_command
        fi
        return 0
    fi
    local commands={}
    COMPREPLY=( $(compgen -W "$commands" -- "${{COMP_WORDS[COMP_CWORD]}}") )
}}
complete -F _jjk_completion jjk
"#,
        sh_quote(&words)
    )
}

fn zsh() -> String {
    let mut script = String::from(
        "#compdef jjk\n# Generated by jjk from its production command registry.\n_jjk_completion() {\n    local -a commands\n    commands=(\n",
    );
    for descriptor in command_descriptors() {
        let candidate = format!("{}:{}", descriptor.claim.name, descriptor.summary);
        writeln!(script, "        {}", sh_quote(&candidate))
            .expect("writing completion to a String cannot fail");
    }
    script.push_str(
        "    )\n    if (( CURRENT == 2 )); then\n        _describe 'jjk command' commands\n    else\n        # Delegate argument completion to Git without claiming Git's grammar.\n        words[1]=git\n        _git\n    fi\n}\ncompdef _jjk_completion jjk\n",
    );
    script
}

fn fish() -> String {
    let mut script = String::from("# Generated by jjk from its production command registry.\n");
    for descriptor in command_descriptors() {
        writeln!(
            script,
            "complete -c jjk -f -n '__fish_use_subcommand' -a {} -d {}",
            sh_quote(descriptor.claim.name),
            sh_quote(descriptor.summary)
        )
        .expect("writing completion to a String cannot fail");
    }
    script.push_str("# Delegate every argument after the registered command to Git's completer.\ncomplete -c jjk -w git -n 'not __fish_use_subcommand'\n");
    script
}

fn powershell() -> String {
    let mut script = String::from(
        "# Generated by jjk from its production command registry.\nRegister-ArgumentCompleter -Native -CommandName jjk -ScriptBlock {\n    param($wordToComplete, $commandAst, $cursorPosition)\n    $elements = @($commandAst.CommandElements)\n    $commands = @(\n",
    );
    for descriptor in command_descriptors() {
        writeln!(
            script,
            "        [pscustomobject]@{{ Name = {}; Description = {} }}",
            powershell_quote(descriptor.claim.name),
            powershell_quote(descriptor.summary)
        )
        .expect("writing completion to a String cannot fail");
    }
    script.push_str(
        "    )\n    if ($elements.Count -gt 2) {\n        # JJK does not own argument grammar; ask PowerShell's native Git completer.\n        $gitLine = 'git ' + (($elements | Select-Object -Skip 2) -join ' ')\n        TabExpansion2 -inputScript $gitLine -cursorColumn $gitLine.Length | Select-Object -ExpandProperty CompletionMatches\n        return\n    }\n    foreach ($command in $commands) {\n        if ($command.Name -like \"$wordToComplete*\") {\n            [System.Management.Automation.CompletionResult]::new(\n                $command.Name,\n                $command.Name,\n                [System.Management.Automation.CompletionResultType]::ParameterValue,\n                $command.Description\n            )\n        }\n    }\n}\n",
    );
    script
}

fn sh_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn powershell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::route::claimed_commands;

    const SHELLS: &[&str] = &["bash", "zsh", "fish", "powershell"];

    #[test]
    fn every_script_is_deterministic_and_registry_derived() {
        let registered = claimed_commands();
        for shell in SHELLS {
            let first = generate_completion(shell).expect("supported shell");
            let second = generate_completion(shell).expect("supported shell");
            assert_eq!(first, second, "{shell}");
            for command in &registered {
                assert!(
                    contains_shell_word(&first, command.name),
                    "{shell}: {}",
                    command.name
                );
            }
        }
    }

    #[test]
    fn scripts_do_not_copy_git_passthrough_commands() {
        for shell in SHELLS {
            let script = generate_completion(shell).expect("supported shell");
            for passthrough in [
                "init", "clone", "log", "diff", "push", "pull", "rebase", "worktree",
            ] {
                assert!(
                    !contains_shell_word(&script, passthrough),
                    "{shell}: {passthrough}"
                );
            }
        }
    }

    #[test]
    fn scripts_only_complete_the_command_position() {
        let bash = generate_completion("bash").expect("bash");
        assert!(bash.contains("COMP_CWORD != 1"));

        let zsh = generate_completion("zsh").expect("zsh");
        assert!(zsh.contains("CURRENT == 2"));

        let fish = generate_completion("fish").expect("fish");
        assert!(fish.contains("__fish_use_subcommand"));

        let powershell = generate_completion("powershell").expect("powershell");
        assert!(powershell.contains("$elements.Count -gt 2"));
    }

    #[test]
    fn aliases_and_unsupported_shells_are_handled_explicitly() {
        assert_eq!(
            generate_completion("pwsh").expect("pwsh alias"),
            generate_completion("powershell").expect("powershell")
        );
        assert_eq!(
            generate_completion("nu")
                .expect_err("unsupported shell")
                .to_string(),
            "unsupported completion shell \"nu\"; expected bash, zsh, fish, or powershell"
        );
    }

    fn contains_shell_word(script: &str, word: &str) -> bool {
        script
            .split(|character: char| !(character.is_ascii_alphanumeric() || character == '-'))
            .any(|candidate| candidate == word)
    }
}
